import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/contexts/auth-context";
import { UserInfoProvider } from "@/contexts/user-info-context";
import { PermissionProvider } from "@/contexts/permission-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <PermissionProvider>
            <UserInfoProvider>
              {children}
            </UserInfoProvider>
          </PermissionProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
